services:

  db_users:
    image: mongo:latest
    container_name: abc_mongo_users
    ports:
      - "27018:27017"

  db_orders:
    image: mongo:latest
    container_name: abc_mongo_orders
    ports:
      - "27019:27017"

  db_payments:
    image: mongo:latest
    container_name: abc_mongo_payments
    ports:
      - "27020:27017"

  users-service:
    build:
      context: ./backend/users-api
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db_users

  order-service:
    build:
      context: ./backend/order-api
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UsersApi__BaseUrl=http://users-service:8080
    depends_on:
      - db_orders
      - users-service

  payment-service:
    build:
      context: ./backend/payment-api
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrdersApi__BaseUrl=http://order-service:8080
    depends_on:
      - db_payments
      - order-service

  frontend:
    build:
      context: ./frontend/abc-order-management
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/abc-order-management:/app
      - /app/node_modules
    environment:
      - NG_CLI_ANALYTICS=false
    command: npm start -- --host 0.0.0.0 --poll 2000
    stdin_open: true
    tty: true
